name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
env:
  # Release tag associated with version of Detekt to be installed
  # SARIF support (required for this workflow) was introduced in Detekt v1.15.0
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build app
        run: ./gradlew assemble

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew lint

      - name: upload html lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results.html

      - name: Run ktlint
        run: ./gradlew app:ktlintCheck --daemon


  unit-test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Unit test
        run: ./gradlew test

      - name: upload test result
        uses: actions/upload-artifact@v2
        with:
          name: Unit test result
          path: app/build/reports/tests/testDebugUnitTest/

  Detekt:
    name: Detekt Scan
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Gets the download URL associated with the $DETEKT_RELEASE_TAG
    - name: Get Detekt download URL
      id: detekt_info
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DETEKT_DOWNLOAD_URL=$( gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
          query getReleaseAssetDownloadUrl($tagName: String!) {
            repository(name: "detekt", owner: "detekt") {
              release(tagName: $tagName) {
                releaseAssets(name: "detekt", first: 1) {
                  nodes {
                    downloadUrl
                  }
                }
              }
            }
          }
        ' | \
        jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl' )
        echo "::set-output name=download_url::$DETEKT_DOWNLOAD_URL"
    # Sets up the detekt cli
    - name: Setup Detekt
      run: |
        dest=$( mktemp -d )
        curl --request GET \
          --url ${{ steps.detekt_info.outputs.download_url }} \
          --silent \
          --location \
          --output $dest/detekt
        chmod a+x $dest/detekt
        echo $dest >> $GITHUB_PATH
    # Performs static analysis using Detekt
    - name: Run Detekt
      continue-on-error: true
      run: ./gradlew detekt

    - name: Upload SARIF to Github
      uses: github/codeql-action/upload-sarif@v1
      if: $
      with:
        sarif_file: build/detekt.sarif

    - name: upload detekt html report
      uses: actions/upload-artifact@v2
      with:
        name: detektReport.html
        path: app/build/reports/detekt/detekt.html